### ISSUE TITLE
how to modify the songs.txt so that the program will read your own lyrics..?

### ISSUE THREAD

**Issue by exploitativetext** [JakubJanowski/Song-Generator#1]
hoping for an answer.

**Comment by JakubJanowski** [comment]
Just paste a song and separate it from another song with #end on a separate line. This is for markov chain to not link the last words of the given song with the first words of the succeeding song.

Also each word is separated by any whitespace characters and any punctuation is considered part of the word, so for example in the line:
_In your head, in your head,they're still fighting,_
the part  _head,they're_ is actually loaded as one word so it may take some editing when copying songs with poorly formatted text.

**Comment by exploitativetext** [comment]
Your work is fantastic, and I find it very useful. I am now wondering about how I might alter the length of the output, or perhaps type in my own set limit for the amount of words..? I am very new to coding, so you may need to walk me through step-by-step. So far, it works great, and I think you've really got something here.

**Comment by JakubJanowski** [comment]
In the file  MainWindow.xaml.cs  find a line 
`for (int i = 1; i < 15; i++) {`
this is the loop for generating pairs of rhyming lines, so just change the 15 to anything you want to generate double the number of lines.

I'm happy to be helpful :)

**Comment by exploitativetext** [comment]
I think I was able to change the length of each line, or lyric, but my essential desire now is to make the "entire lyric" -- the whole song, to a much longer script. I want to generate an extremely large song, basically, and wish to know how to make the entire song in its complete form, longer. Is there a limit, and could I potentially generate up to a dozen pages of lyrics at once..?

**Comment by JakubJanowski** [comment]
There is no such limit. I've modified the function in the main file
_MainWindow.xaml.cs_. You can copy the attached file content and paste it
in place of the original function. Now you can simply edit the values of
the two variables: _numberOfLines_ and _numberOfSyllablesInLine_. Their
purposes can be deducted from their names. I hope it will work as supposed
to because I'm unable to test it right now.

If you would like to know anything else feel free to ask.

Regards

(https://github.com/JakubJanowski/Song-Generator/files/434113/copy.this.txt)
