### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by exploitativetext** [JakubJanowski/Song-Generator#2]
Jakub,

Being that I think songwriters and lyricists could potentially benefit from the creative support, I think this code is very useful, and was wondering about some other changes.

Having altered the code, and followed your suggestions, I've learned how to use it to a point where I feel that it is something which could be completed with an improved GUI, and maybe one or two more functions in regards to the songs.txt and unique words.txt files.

The two changes I think the program could use:

A textbox, with a button, to edit the songs.txt file. 

The example songs.txt could still be used.

A textbox, with a button, to edit the unique words.txt file. The example unique words would still also probably be used, to show how it is to be properly edited without punctuation or spaces.

Or maybe a "help" textbox, to say how to edit each txt file.

With these two changes, I think the program would be greatly improved. Do you have the time to work on the forms, and edit the GUI to make these changes..? I am only learning code presently, but wanting to speed up this project, don't really know where to start without your suggestions or perhaps even wondering if you could make these changes yourself..? I see no other changes needed to the program, and also am quite interested in knowing about its future, or where it might be headed as far as being shared with other people, and artists who may find it useful. ?

If, you can make the changes, let me know, and if not, please at least help assist me perhaps in making them myself..?

(I have spoken with other programmers involved in Markov-related projects, and see that some of their projects are now defunct, and no longer being given much attention. I am not sure about the state of your project, but as far as its future, license, domain, sharing, or what "I" could do with this program myself, as far as sharing it with other people, I would be interested to know what you have to say about it, since I like it so much I, and enjoy using it so much.)

Let me know.

-Brendan

**Comment by JakubJanowski** [comment]
Hi Brendan,

thank you for the feedback! Song-Generator was a group project made for Artificial Intelligence subject at my university so in fact the GUI is minimalistic, just enough to show the functionality.

Unfortunately right now I'm working on another project that has a higher priority for me, but I'm looking forward to creating something bigger from Song-Generator in some time, maybe next year.

If you want to extend the GUI yourself, just use the visual studio's editor to add the new elements and write the functions for new buttons analogously to the two already being in there. As for the _unique words.txt_ file, it is not used in the programs logic ;) I just forgot to remove it. Program entirely depends only on the songs.txt and db.bin file which acts as a dictionary providing phoneme representations of words used in rhymes. To add custom words to the dictionary you would have to dive really deep into the algorithm, if you want I could try to explain that too.

About editing the songs.txt during the program run, I would add new textbox and a save button (maybe a load button too to be able to specify different files). In the button's click action you would have to perform a simple save (load) action to (from) file. After modification a call to the function _MarkovChains.CreateMarkovChain(text)_ (with _text_ being the whole content of _songs.txt_) is needed for changes to take place.

For the future of the program I suppose I would make it find more sophisticated rhymes constructed from more than one word which often happens to be just one syllable, also to feature different rhyme schemes, not only the plain aabb type.

Coming to the license part, I'm not good with licenses, but I updated the LICENSE file to state GPL 2 because as I have read I'm forced to use it after including part of Bradley Buda's algorithm for determining syllable similiarity.

Regards,

Jakub

**Comment by exploitativetext** [comment]
Great, thanks for all the information. I am presently altering the code, and have made adjustments where it is simplified to 6 words 6 lines, for the use of poetry, to be honest, and the generations are great in spite of the amount of work put into this program so far. If I were to "share" a series of poems, now, written with this program, I am now wondering about licensing, copyright, or with respect, if you think that is unnecessary, still, with whom I should still credit because I respect the software, and its every programmer involved so much. My question is: to "share" a book of poems, written from the program, and what kind of legality would be involved in this, whether free, or sold..? I know very little about licensing as well, and have very little knowledge of the world of publishing save for my own resources. The words are my own, but they are not produced entirely by my own programming obviously, and since I respect the creator of something so much, I wish to know as much as I probably should in the case of sharing my written work. Let me know, at your leisure. Maybe an interesting question..? If you are also, interested in having my text, once it is finished, I can also probably find a way to get you a private copy. Thanks!

-Brendan

**Comment by JakubJanowski** [comment]
I'm glad to hear that my work helped you so much. If it were to be published I would be more than happy if I could be linked in your work along with Maciej Khuat Cao and Artur Furmańczyk who were also creating the program with me. Apart from that I think that you can do with your book whatever you want (should it be free or not) as even if the GPL license would apply, I wouldn't have anything against.

I'm really interested in that masterpiece you are creating and I wouldn't despise your offer to let me read it when it's finished :)
